---
title: "Combining a data dictionairy with a data frame"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)
```

Here an example data dictionary is defined and an example data frame. 

```{r}
data_dictionary <- tibble(
  column_name = c(rep("geslacht", 3), rep("commal1", 4)),
  value = c(1, 2, 3, 1, 2, 3, 4),
  description = c(
    "Man", "Vrouw", "Ongedifferentieerd", "Ja, actueel",
    "Ja, curatief behandeld < 5j geleden", "Ja, curatief behandeld > 5j geleden",
    "Ja, palliatief behandeld"
  )
)
data_dictionary
data <- tibble(
  patient_id = seq(1, 8), 
  geslacht = c(1, 2, 3, 1, 2, 3, 1, 2),
  commal1 = c(1, 2, 3, 4, 1, 2, 3, 4)
)
data
```

Now it is shown how the values in the data frame can be replaced with the labels in the data dictionairy.

```{r}
data_description <- data %>%
  gather("column_name", "value", -patient_id) %>%
  left_join(data_dictionary, by = c("column_name", "value")) %>%
  select(-value) %>%
  spread(column_name, description)
data_description
```

