# For DataFrames

## Make a dataframe with: name, films, episode_ids of the films, number of films, height, species

```{r}
people_df <- as_data_frame(people[2:3])

people_df <- data_frame(
  name = map_chr(people, "name"),
  films = map(people, "films"),
  height = map_chr(people, "height") %>%
    readr::parse_number(na = "unknown"),
  species = map_chr(people, "species", .null = NA_character_)
)

people_df$films

film_number_lookup <- films %>%
  map_int("episode_id") %>%
  set_names(map_chr(films, "url"))

people_df <- people_df %>%
  mutate(
    film_numbers = map(films, ~ film_number_lookup[.x]),
    n_films = map_int(films, length)
  )
```

# Put the film number in one string in one column

```{r}
#do it for one
paste(people_df$film_numbers[[1]], collapse = ", ")

people_df <- people_df %>%
  mutate(films_squashed = map_chr(film_numbers, paste, collapse = ", "))
```

# map2()

```{r}
# Explore time series -----------------------------------------------------
head(per_day[[1]])
ggplot(per_day[[1]], aes(trmt_date, count)) + geom_line()


plots <- map(per_day, ~ ggplot(.x, aes(trmt_date, count)) + geom_line())
plots

# see plots
walk(plots, print)

# save plots
walk2(paste0("./", common_codes, ".png"),
  plots, ggsave, width = 10, height = 3)

# Use map2 to add titles
plots_with_titles <- map2(per_day, common_names, 
  ~ qplot(trmt_date, count, data = .x, geom = "line") + ggtitle(.y))

plots_with_titles[[1]]

# Fit naive models
models <- map(per_day, ~ lm(count ~ month + wday, data = .x))

map2_dbl(models, per_day, modelr::rsquare)

accidents <- tibble(
  name = common_names,
  code = common_codes,
  data = per_day)

accidents %>%
  mutate(
    model = map(data, ~ lm(count ~ month + wday, data = .x)),
    rsquare = map2_dbl(model, data, modelr::rsquare)) %>%
  arrange(rsquare) %>% 
  select(name, rsquare)


# Why does rsquare take two arguments?
# so you can do this kind of thing
accidents <- accidents %>% 
  mutate(
    train = map(data, ~ filter(.x, trmt_date < "2014-01-01")),
    test = map(data, ~ filter(.x, trmt_date >= "2014-01-01")),
    model = map(train, ~ lm(count ~ month + wday, data = .x)))

accidents <- accidents %>% 
  mutate(
    rsquare_test = map2_dbl(model, test, modelr::rsquare)
  )

accidents %>% arrange(rsquare_test) %>% select(name, rsquare_test)
```

