---
title: "Diamonds"
output: html_notebook
---

```{r}
library(tidyverse)
diamonds <- as_data_frame(diamonds)
```

1. Describe the distribution of the `price` variable

```{r}
ggplot(diamonds) +
  geom_histogram(aes(price))
```

1. How many diamonts are there per type?

```{r}
diamonds %>%
  group_by(cut) %>%
  summarise(n = n())

diamonds %>%
  count(cut)

ggplot(diamonds) +
  geom_bar(aes(cut))
```

1. Show the relation between the `depht` and `price` only for the `fair` diamonds.

```{r}
diamonds %>%
  filter(cut == "Fair") %>%
  ggplot(aes(depth, price)) +
  geom_point() +
  geom_smooth(method = "lm")

fair_diamonds <- diamonds %>%
  filter(cut == "Fair") 

model <- lm(price ~ depth, fair_diamonds)
summary(model)
```

1. For every type of diamond calculate the following variables:
  * minimal `price`
  * maximal `price`
  * mean `price`
  * median `price`

```{r}
diamonds %>%
  group_by(cut) %>%
  summarise(min = min(price),
            max = max(price),
            mean = mean(price),
            median = median(price))
```
