---
title: "Extra Join Exersice Answers"
output: html_notebook
---

```{r, include=FALSE}
library(tidyverse)
library(nycflights13)
flights <- flights %>%
  sample_n(20000)
airports <- as_tibble(airports)
```

1. Show in a plot the distribution of the difference in altitude between the `origin` airport and the `dest` airport. You can you the `flights` and the `airports` data frames for that.

```{r}
flights %>%
  left_join(airports, c("dest" = "faa")) %>%
  select(origin, dest, dest_alt = alt) %>%
  left_join(airports, c("origin" = "faa")) %>%
  mutate(alt_diff = dest_alt - alt) %>%
  ggplot() +
  geom_histogram(aes(alt_diff), binwidth = 100)
```

2. Replace the numeric values in the columns in the `data` with the corresponding descriptions from the `data_dictionary`.

```{r}
data_dictionary <- tibble(
  column_name = c(rep("geslacht", 3), rep("commal1", 4)),
  value = c(1, 2, 3, 1, 2, 3, 4),
  description = c(
    "Man", "Vrouw", "Ongedifferentieerd", "Ja, actueel",
    "Ja, curatief behandeld < 5j geleden", 
    "Ja, curatief behandeld > 5j geleden",
    "Ja, palliatief behandeld"
  )
)
data <- tibble(
  patient_id = seq(1, 8), 
  geslacht = c(1, 2, 3, 1, 2, 3, 1, 2),
  commal1 = c(1, 2, 3, 4, 1, 2, 3, 4)
)
data_description <- data %>%
  gather("column_name", "value", -patient_id) %>%
  left_join(data_dictionary, by = c("column_name", "value")) %>%
  select(-value) %>%
  spread(column_name, description)
```

