---
title: "Tidy Exersice Answers"
output: html_notebook
---

```{r, include=FALSE}
library(tidyverse)
```

Make tidy the two following datasets.

```{r}
weather <- read_csv(
  "../../datasets/weather.csv",
  col_types = list(
    .default = col_integer(),
    id = col_character(),
    element = col_character()
  )
)
pew <- read_csv(
  "../../datasets/pew.csv",
  col_types = list(
    .default = col_double(),
    religion = col_character()
  )
)
```

```{r}
weather %>%
  gather("day", "temperature", d1:d31, na.rm = TRUE) %>%
  spread("element", "temperature") %>%
  separate(day, c("d", "day"), sep = 1) %>%
  select(-d, -id) %>%
  mutate(day = as.numeric(day))
```

```{r}
pew %>%
  gather("income", "count", 2:11)
```

# More Gather

Calculate for every group the percentages of 1's for every column.

```{r}
df <- tibble(
  "group" = rep(1:5, 4),
  "a" = sample(0:1, 20, replace = TRUE),
  "b" = sample(0:1, 20, replace = TRUE),
  "c" = sample(0:1, 20, replace = TRUE)
)

df %>%
  gather("key", "value", -group) %>%
  group_by(group, key) %>%
  summarise(perc_1 = sum(value) / n()) %>%
  spread(key, perc_1)
```
